require_relative '../models/admin'


class Admins < Angus::BaseResource

  ADMINS = [
    Admin.new(1, 'John Smith', 33),
    Admin.new(2, 'John Doe', 44)
  ]

  def show
    user = ADMINS.find { |user| user[:id] == params[:id].to_i }

    {:profile => user}
  end

  def index
    { :users => ADMINS }
  end

  def create
    user = Admin.new(last_id, params[:name], params[:age])

    { :user => user }
  end

  protected

  # This is not a good practice is only for testing propose. Use an
  #   autogenerated id (using db features).
  def last_id
    ADMINS.map {|user| user['id'] }.max + 1
  end

end